name: tailnflows 
channels:
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - jupyter
  - matplotlib
  - numpy
  - scipy
  - tqdm
  - pandas
  - pip>=3.0.0
  - pip:
    - posteriordb
    - git+https://github.com/Tennessee-Wallaceh/nflows
    - flowtorch==0.5